---
pg_username: postgres
pg_password: postgres
pg_source_db: source_pg_db
pg_backup_dir: /tmp/backup
pg_backup_file: "{{ 'backup_file-' ~ ansible_date_time.date ~ '-' ~ ansible_date_time.hour ~ ansible_date_time.minute ~ '.gz' }}"
pg_dest_db: destination_pg_db
